#!/usr/bin/env python2
#coding=utf-8

import os, sys, urllib, urllib2, json

baseurl = 'http://fanyi.youdao.com/translate?smartresult=dict&smartresult=rule&smartresult=ugc&sessionFrom=plugin&type=AUTO&doctype=json&xmlVersion=1.6&keyfrom=fanyi.web&ue=UTF-8&typoResult=true&i='

if len(sys.argv) < 2:
    print 'without args'
    exit(-1)

query = []
for q in sys.argv[1:]:
    query.append(urllib.quote_plus(q))

target = baseurl + '%20'.join(query)
json = json.loads(urllib2.urlopen(target).read())

if json.has_key('translateResult'):
    org = json['translateResult'][0][0]
    print "%s => %s" % (org['src'], org['tgt'])

if json.has_key('smartResult'):
    item = json['smartResult']['entries']
    print "\n".join(item[1:])

print "delayed: %sms" % json['elapsedTime']

